spring.application.name=Project007

spring.datasource.url=jdbc:mysql://localhost:3306/StudentINFO
spring.datasource.username=root
spring.datasource.password=@20May2007
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
